Search User Location in Landing Page
UPRI-NOAH/noah-frontend pull request #119
Opened 2021-08-10 08:21 UTC by bon-carpo

# To DO's

- [x] Only ask for the location of the user when the user actually clicks "Your Current Location"
- [x] Show the dropdown when the user clicks the search input field (i.e., the search input field is on focus)
- [x] Allow up and down using arrow key in dropdown selection
- [x] Fix UI Navigation
- [ ] Display Current location inside search input in KYH page when "Your Current Location" is selected and fly to kyh

# Screenshots

## Search Input on Focus
![image](https://user-images.githubusercontent.com/76890692/128833888-9424e07b-633d-4aae-9d0f-e4f67509cf11.png)

## Navigation Old
![image](https://user-images.githubusercontent.com/76890692/128833605-2d96e191-eeb9-4316-8fdf-fe33de0f12e7.png)

## Navigation New
![image](https://user-images.githubusercontent.com/76890692/128833783-3f57812b-9cd7-4f9b-8c48-6020a4af36f3.png)

2021-09-06 10:05 UTC, kennethliporada commented
# Description
- reverse geocode user coordinates from localstorage
-  stored reverse geocode value to localstorage
- changing placeholder from user location to kyh page search
- changing placeholder from selected place to kyh page search

# Loom
- https://www.loom.com/share/f9ea2e9142ef40669e9e1f56106c05dd

# Encounter Error inside KYH page
- https://www.loom.com/share/27302802c4f8457ca26909004fc71d50

# Errors
- inside kyh page di napapalitan yung placeholder kapag na select na yung user location
- from landing page kapag nag select ng place at napunta sa kyh page then na back nandun pa rin yung placeholder na naselect mo.

2021-09-07 09:25 UTC, kennethliporada commented
# Description
Fixed Errors:
- `inside kyh page di napapalitan yung placeholder kapag na select na yung user location`
-  `from landing page kapag nag select ng place at napunta sa kyh page then na back nandun pa rin yung placeholder na naselect mo`.

# Loom
https://www.loom.com/share/d1f9b027aad24d13853e22348757d261

# Error
- inside kyh kapag nag select ng other place then nag click ng `Your Location` hindi nag ccenter

2021-09-12 01:34 UTC, jadurani requested changes

2021-09-14 03:58 UTC, kennethliporada commented on src/app/features/know-your-hazards/services/kyh.service.ts
> +  keyBoard: Subject<any> = new Subject<any>();
to read arrow keys po yan.

2021-09-22 07:00 UTC, kennethliporada commented
# Description
- getting userlocation with reverse geocode
- display placeholder to kyh page
- move arrow keys up, down and select using enter key
- stored user coordinates and user place name to the localstorage
- deleted unused variables and console logs

# Loom 
https://www.loom.com/share/b96ad5351ad64d0bbdec4140873f7881

2021-09-29 15:07 UTC, jadurani commented
reworked at https://github.com/UPRI-NOAH/noah-frontend/pulls

2021-09-29 15:07 UTC, closed without merging