Feat/iot sensor
UPRI-NOAH/noah-frontend pull request #274
Opened 2022-05-24 07:31 UTC by kennethliporada

#Description Overall
- IOT Sensors Tab
> - Change options to checkbox button
> - Set Flood Sensor as default layer once IOT Sensor is clicked
> - Change naming for options for IOT
> - Finalize legend color for dots

- IOT Graph/Chart
> Add burger menu for download image and csv
> Change background color of data in graph
> Change datetime display in Y-axis
> X-axis should be the value of the data
> Add title as location inside the graph
> Can hide/show when you click the flood sensor inside chart pop-up
> Once the user hover on the dots, it shows the pop-up summary details
> On click of the dots, it shows pop-up graph/chart
> Once the graph/chart pop-up, the user can hover inside the graph/chart
> Change size of the dots in the map as per instructions by Sir mahar

2022-05-24 08:44 UTC, kennethliporada commented
# Description
- fix css for X button upper right side of the chart

# Screenshot
- Old
![image](https://user-images.githubusercontent.com/62271587/169989723-89fe920b-739b-4829-891a-3227ae04c01a.png)

- New
- 
![image](https://user-images.githubusercontent.com/62271587/169989785-70aace50-1482-4141-8675-2ed5248aab78.png)

2022-05-24 11:05 UTC, kennethliporada commented
# Description
- close button inserted margin right

# Photo
![image](https://user-images.githubusercontent.com/62271587/170019608-519e96f4-b750-4468-96f3-4ca48e0d1a9c.png)

# Additional edited
- I also put a code on the sensor because when I put a code for the sensor font, so what I put on the iot is what I put into the sensor.

2022-05-25 02:28 UTC, kennethliporada commented
# Description
- changed base URL to 'https://noah-api.up.edu.ph/'

![image](https://user-images.githubusercontent.com/62271587/170166627-063ddba6-aad7-4afa-9449-a8ee94861a0e.png)

2022-05-25 02:30 UTC, bon-carpo requested changes
delete line 64 and 66

2022-05-25 03:10 UTC, bon-carpo requested changes
@kennethliporada kindly check my comments. Thank you

2022-05-25 03:10 UTC, bon-carpo commented on src/app/features/noah-playground/services/qc-sensor-chart.service.ts
> +  }
remove all  unused line/s

2022-05-25 03:10 UTC, bon-carpo commented on src/app/features/noah-playground/services/qc-sensor-chart.service.ts
> +  }
@kennethliporada remove all unused line/s

2022-05-25 03:10 UTC, bon-carpo commented on src/app/features/noah-playground/components/qc-sensors-group/qc-sensors-group.component.html
> +    </div> -->
remove line 87 to 92

2022-05-25 03:10 UTC, bon-carpo commented on src/app/features/noah-playground/components/qc-sensor-solo/qc-sensor-solo.component.ts
> +  // sensor_1: 'Sensor_1'
remove line 12 and 13

2022-05-25 03:10 UTC, bon-carpo commented on src/app/features/noah-playground/components/qc-sensor-solo/qc-sensor-solo.component.scss
> +// }
remove all unused line/s

2022-05-25 03:10 UTC, bon-carpo commented on src/app/features/noah-playground/components/qc-sensor-solo/qc-sensor-solo.component.html
> +</div> -->
remove line 30 to 46

2022-05-25 03:10 UTC, bon-carpo commented on src/app/features/noah-playground/components/map-playground/map-playground.component.ts
>  // hazardShown$: Observable<boolean>;
remove line 106 and 107

2022-05-25 03:33 UTC, kennethliporada commented
# Description
- Deleted unused codes and comments

2022-05-25 03:57 UTC, merged